SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `gallery` (
  `gid` int(11) NOT NULL,
  `token` char(10) NOT NULL,
  `archiver_key` varchar(60) NOT NULL,
  `title` varchar(200) NOT NULL,
  `title_jpn` varchar(200) NOT NULL,
  `category` varchar(15) NOT NULL,
  `thumb` varchar(150) NOT NULL,
  `uploader` varchar(50) DEFAULT NULL,
  `posted` int(11) NOT NULL,
  `filecount` int(11) NOT NULL,
  `filesize` int(11) NOT NULL,
  `expunged` tinyint(1) NOT NULL,
  `rating` char(4) NOT NULL,
  `torrentcount` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `gid_tid` (
  `gid` int(11) NOT NULL,
  `tid` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tag` (
  `id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


ALTER TABLE `gallery`
 ADD PRIMARY KEY (`gid`);

ALTER TABLE `tag`
 ADD PRIMARY KEY (`id`);


ALTER TABLE `tag`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
